# Generated by Django 5.0.6 on 2024-05-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
