# Generated by Django 5.0.6 on 2024-05-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.SmallIntegerField(max_length=20),
        ),
    ]
