# Generated by Django 5.0.6 on 2024-05-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0011_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
