# Generated by Django 5.0.6 on 2024-05-16 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photostore', '0012_alter_product_price_alter_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15),
        ),
    ]
